#!/usr/bin/env python3
import argparse
import json
import os
from typing import Any, Dict, List, Optional, Tuple


def _read_json(path: str) -> Optional[Any]:
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:  # pylint: disable=broad-except
        return None


def _classify_indices(traj: List[Dict[str, Any]]) -> Tuple[List[int], List[int]]:
    """Classify indices in traj.json into error and correct.

    Heuristic:
    - A record is considered "correct" if:
      - result["exit_code"] == 0, AND
      - result["summary"].get("correctness", True) is truthy (if present).
    - Otherwise it is considered "error".
    """
    error_indices: List[int] = []
    correct_indices: List[int] = []

    for idx, rec in enumerate(traj):
        result = rec.get("result") or {}
        if not isinstance(result, dict):
            error_indices.append(idx)
            continue

        exit_code = result.get("exit_code")
        summary = result.get("summary") or {}
        if not isinstance(summary, dict):
            summary = {}

        correctness = summary.get("correctness")
        is_correct = exit_code == 0 and (correctness is True or correctness is None)

        if is_correct:
            correct_indices.append(idx)
        else:
            error_indices.append(idx)

    return error_indices, correct_indices


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze a traj.json file and report the number and indices of "
            "error codes and correct codes."
        ),
    )
    parser.add_argument(
        "--traj_path",
        type=str,
        required=True,
        help="Path to traj.json generated by scripts/verify.py.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Optional path to save the analysis result as JSON. "
            "If not provided, the result will be printed to stdout."
        ),
    )

    args = parser.parse_args()
    traj_path = os.path.abspath(args.traj_path)

    data = _read_json(traj_path)
    if not isinstance(data, list):
        print(f"[get_error_code_num] ERROR: traj_path does not contain a list: {traj_path}")
        return 1

    error_indices, correct_indices = _classify_indices(data)

    result: Dict[str, Any] = {
        "traj_path": traj_path,
        "total": len(data),
        "error_count": len(error_indices),
        "error_indices": error_indices,
        "correct_count": len(correct_indices),
        "correct_indices": correct_indices,
    }

    if args.output:
        output_path = os.path.abspath(args.output)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        print(f"[get_error_code_num] Result saved to {output_path}")
    else:
        # Print a JSON object so that the agent can easily parse it.
        print(json.dumps(result, ensure_ascii=False, indent=2))

    # The caller (agent) will decide whether to continue based on the counts.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

